INSERT INTO tag (name)
VALUES ('jollof rice'),
       ('suya'),
       ('pounded yam'),
       ('fufu'),
       ('garri'),
       ('egusi soup'),
       ('efo riro'),
       ('akara'),
       ('moimoi'),
       ('ofada rice'),
       ('amala'),
       ('ogbono soup'),
       ('banga soup'),
       ('pepper soup'),
       ('nkwobi'),
       ('isi ewu'),
       ('plantain chips'),
       ('chin chin'),
       ('puff puff'),
       ('kokoro'),
       ('masa'),
       ('zobo'),
       ('kunu'),
       ('sobo drink'),
       ('palm oil'),
       ('groundnut oil'),
       ('fresh fish'),
       ('tilapia'),
       ('stockfish'),
       ('dried fish'),
       ('bush meat'),
       ('fresh meat'),
       ('chicken'),
       ('goat meat'),
       ('yam tuber'),
       ('cassava'),
       ('cocoyam'),
       ('plantain'),
       ('okra'),
       ('ugu'),
       ('bitterleaf'),
       ('scent leaf'),
       ('uziza leaf'),
       ('crayfish'),
       ('garri eba'),
       ('banku'),
       ('tuwo masara'),
       ('wheat flour'),
       ('semovita'),
       ('semo'),
       ('semolina'),
       ('fufu flour'),
       ('spaghetti'),
       ('indomie'),
       ('noodles'),
       ('rice'),
       ('beans'),
       ('sugar'),
       ('salt'),
       ('tomatoes'),
       ('onions'),
       ('garlic'),
       ('ginger'),
       ('pepper'),
       ('seasoning cube'),
       ('crayfish powder'),
       ('africano coffee'),
       ('akara soup'),
       ('fish pepper soup'),
       ('ankara fabric'),
       ('aso-ebi'),
       ('gele'),
       ('wrapper'),
       ('agbada'),
       ('buba'),
       ('iro'),
       ('sokoto'),
       ('dashiki'),
       ('adire'),
       ('shoe shine'),
       ('haircut'),
       ('barber'),
       ('tailor'),
       ('boutique'),
       ('beauty salon'),
       ('spa'),
       ('pharmacy'),
       ('chemist'),
       ('clinic'),
       ('hospital'),
       ('ATM'),
       ('bank branch'),
       ('petrol station'),
       ('grocer'),
       ('electronics'),
       ('phone repair'),
       ('internet café'),
       ('bookstore'),
       ('stationery'),
       ('photocopy shop')
ON CONFLICT DO NOTHING;
