package com.ahmad.ProductFinder.dtos.request;

import com.ahmad.ProductFinder.models.Role;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import io.swagger.v3.oas.annotations.media.Schema; // Import the Schema annotation

import java.time.LocalDateTime;
import java.util.Collection;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Schema(
        name = "CreateUserRequest",
        description = "Request DTO for registering a new user."
)
public class CreateUserRequestDto {

    @Schema(description = "The user's email address (must be unique)", example = "john.doe@example.com", requiredMode = Schema.RequiredMode.REQUIRED)
    private String email;

    @Schema(description = "The user's first name", example = "John", requiredMode = Schema.RequiredMode.REQUIRED)
    private String firstName;

    @Schema(description = "The user's last name", example = "Doe", requiredMode = Schema.RequiredMode.REQUIRED)
    private String lastName;

    @Schema(description = "A unique username for the user", example = "johndoe", requiredMode = Schema.RequiredMode.REQUIRED)
    private String username;

    @Schema(description = "The user's password (should meet complexity requirements)", example = "StrongP@ss123", requiredMode = Schema.RequiredMode.REQUIRED)
    private String password;

    @Schema(description = "The user's phone number", example = "+2348012345678", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    private String phoneNumber;

    @Schema(description = "A collection of roles assigned to the user (e.g., ADMIN, USER, STORE_OWNER)",
            example = "[\"USER\"]")
    private Collection<Role> role;

    @Schema(description = "The timestamp when the user account was created (auto-generated by the backend)",
            type = "string", format = "date-time", example = "2024-06-13T10:30:00Z",
            requiredMode = Schema.RequiredMode.NOT_REQUIRED)
    private LocalDateTime createdAt;
}